import json
import os
import re
import threading
import urllib.error
import urllib.request
from datetime import date, datetime, timedelta

from models.database import connect
from services.system_calendar import holidays


SYNC_ENABLED = os.environ.get("GENERATED_CALENDAR_SYNC_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
SYNC_INTERVAL_SECONDS = max(3600, int(os.environ.get("GENERATED_CALENDAR_SYNC_INTERVAL_SECONDS", "86400")))
ADAPTER_URL = os.environ.get("CALENDAR_ADAPTER_INTERNAL_URL", "http://100.94.208.16:8091").rstrip("/")
TIMEOUT_SECONDS = float(os.environ.get("BRAIN_UPSTREAM_TIMEOUT_SECONDS", "30"))

SYSTEM_CATEGORY = "KAOS-SYSTEM"
GENERATED_CATEGORY = "KAOS-GENERATED-CALENDAR"
MARKET_CATEGORY = "KAOS-MARKET-DAY"
MARKET_SATURDAY_CATEGORY = "KAOS-MARKET-SATURDAY"
CLAIM_CATEGORY = "KAOS-CLAIM-DAY"
MARKET_DAYS = {5, 10, 15, 20, 25, 30}

_state_lock = threading.Lock()
_sync_lock = threading.Lock()
_scheduler_thread = None
_scheduler_wake = threading.Event()
_state = {
    "running": False,
    "lastAttemptAt": "",
    "lastSuccessAt": "",
    "lastError": "",
    "lastResult": {},
}


def _now_iso():
    return datetime.now().astimezone().isoformat(timespec="seconds")


def is_market_day(value):
    return value.day in MARKET_DAYS


def dates_in_year(year):
    current = date(year, 1, 1)
    end = date(year + 1, 1, 1)
    while current < end:
        yield current
        current += timedelta(days=1)


def market_dates(year):
    return [value for value in dates_in_year(year) if is_market_day(value)]


def claim_date_for_friday(friday, public_dates=None):
    public_dates = set(public_dates or ())
    saturday = friday + timedelta(days=1)
    candidate = saturday if is_market_day(saturday) and saturday not in public_dates else friday
    while candidate in public_dates:
        candidate -= timedelta(days=1)
    return candidate


def claim_weeks(year, public_dates=None):
    first = date(year, 1, 1)
    friday = first + timedelta(days=(4 - first.weekday()) % 7)
    result = []
    while friday.year == year:
        result.append((friday, claim_date_for_friday(friday, public_dates)))
        friday += timedelta(days=7)
    return result


def market_uid(value):
    return f"KAOS-MARKET-{value.isoformat()}"


def claim_uid(friday):
    return f"KAOS-CLAIM-WEEK-{friday.isoformat()}"


def market_event(value):
    categories = [SYSTEM_CATEGORY, GENERATED_CATEGORY, MARKET_CATEGORY]
    if value.weekday() == 5:
        categories.append(MARKET_SATURDAY_CATEGORY)
    return {
        "uid": market_uid(value),
        "title": "Market Day",
        "memo": "Generated by KaosGDD Brain",
        "startDate": value.isoformat(),
        "endDate": value.isoformat(),
        "categories": categories,
    }


def claim_event(friday, value):
    return {
        "uid": claim_uid(friday),
        "title": "Claim Day",
        "memo": "Generated by KaosGDD Brain",
        "startDate": value.isoformat(),
        "endDate": value.isoformat(),
        "categories": [SYSTEM_CATEGORY, GENERATED_CATEGORY, CLAIM_CATEGORY],
    }


def desired_events(years, public_dates, settings):
    items = []
    for year in sorted(set(years)):
        if settings["marketDaysEnabled"]:
            items.extend(market_event(value) for value in market_dates(year))
        if settings["claimDayEnabled"]:
            items.extend(claim_event(friday, value) for friday, value in claim_weeks(year, public_dates))
    return sorted(items, key=lambda item: (item["startDate"], item["uid"]))


def get_settings():
    with connect() as connection:
        row = connection.execute(
            """
            SELECT market_days_enabled, claim_day_enabled, updated_at
            FROM generated_calendar_settings
            WHERE id = 1
            """
        ).fetchone()
    if not row:
        raise RuntimeError("generated_calendar_settings_missing")
    return {
        "marketDaysEnabled": bool(row[0]),
        "claimDayEnabled": bool(row[1]),
        "updatedAt": row[2].isoformat() if row[2] else "",
    }


def update_settings(payload):
    if not isinstance(payload, dict):
        raise ValueError("invalid_payload")
    current = get_settings()
    market_enabled = payload.get("marketDaysEnabled", current["marketDaysEnabled"])
    claim_enabled = payload.get("claimDayEnabled", current["claimDayEnabled"])
    if not isinstance(market_enabled, bool) or not isinstance(claim_enabled, bool):
        raise ValueError("invalid_custom_event_setting")
    with connect() as connection:
        row = connection.execute(
            """
            UPDATE generated_calendar_settings
            SET market_days_enabled = %s,
                claim_day_enabled = %s,
                updated_at = now()
            WHERE id = 1
            RETURNING market_days_enabled, claim_day_enabled, updated_at
            """,
            (market_enabled, claim_enabled),
        ).fetchone()
    return {
        "marketDaysEnabled": bool(row[0]),
        "claimDayEnabled": bool(row[1]),
        "updatedAt": row[2].isoformat() if row[2] else "",
    }


def _adapter_request(method, payload=None):
    body = None if payload is None else json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        f"{ADAPTER_URL}/internal/zin/generated-events",
        data=body,
        method=method,
        headers={"Accept": "application/json", "User-Agent": "KaosGDD-Brain/generated-calendar"},
    )
    if body is not None:
        request.add_header("Content-Type", "application/json; charset=utf-8")
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
            status_code = response.status
            result = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        try:
            result = json.loads(exc.read().decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            result = {"error": f"calendar_adapter_http_{status_code}"}
    if status_code >= 400 or not result.get("ok"):
        raise RuntimeError(result.get("error") or f"calendar_adapter_http_{status_code}")
    return result


def _normalized_categories(item):
    return sorted(str(value).strip().upper() for value in item.get("categories", []) if str(value).strip())


def _event_matches(current, wanted):
    return (
        str(current.get("summary") or current.get("title") or "") == wanted["title"]
        and str(current.get("description") or current.get("memo") or "") == wanted["memo"]
        and str(current.get("startDate") or "") == wanted["startDate"]
        and str(current.get("endDate") or current.get("startDate") or "") == wanted["endDate"]
        and _normalized_categories(current) == sorted(wanted["categories"])
    )


def _uid_year(uid):
    match = re.fullmatch(r"KAOS-(?:MARKET|CLAIM-WEEK)-(\d{4})-\d{2}-\d{2}", str(uid or "").upper())
    return int(match.group(1)) if match else None


def sync_generated_calendar(today=None):
    today = today or date.today()
    years = {today.year, today.year + 1}
    with _sync_lock:
        with _state_lock:
            _state["running"] = True
            _state["lastAttemptAt"] = _now_iso()
            _state["lastError"] = ""
        try:
            settings = get_settings()
            holiday_items = holidays.list_holidays().get("items", [])
            public_dates = {
                date.fromisoformat(item["startDate"])
                for item in holiday_items
                if item.get("publicHoliday") and str(item.get("startDate") or "")[:4].isdigit()
            }
            desired = desired_events(years, public_dates, settings)
            desired_by_uid = {item["uid"]: item for item in desired}
            existing_result = _adapter_request("GET")
            existing = {str(item.get("uid") or "").upper(): item for item in existing_result.get("items", [])}
            created = updated = unchanged = deleted = 0

            for uid, item in desired_by_uid.items():
                current = existing.get(uid)
                if current and _event_matches(current, item):
                    unchanged += 1
                    continue
                result = _adapter_request("PUT", item)
                created += int(bool(result.get("created")))
                updated += int(not result.get("created"))

            for uid in sorted(existing):
                if uid in desired_by_uid or _uid_year(uid) not in years:
                    continue
                result = _adapter_request("DELETE", {"uid": uid})
                deleted += int(bool(result.get("deleted")))

            result = {
                "created": created,
                "updated": updated,
                "unchanged": unchanged,
                "deleted": deleted,
                "total": len(desired),
                "years": sorted(years),
            }
            with _state_lock:
                _state["lastSuccessAt"] = _now_iso()
                _state["lastResult"] = result
            return {"ok": True, "settings": settings, **result}
        except Exception as exc:
            with _state_lock:
                _state["lastError"] = str(exc) or type(exc).__name__
            raise
        finally:
            with _state_lock:
                _state["running"] = False


def settings_payload():
    return {"ok": True, "settings": get_settings(), "sync": status()}


def status():
    with _state_lock:
        return {"configured": bool(ADAPTER_URL), "enabled": SYNC_ENABLED, **_state}


def scheduler_loop():
    while True:
        try:
            sync_generated_calendar()
        except Exception as exc:
            print(f"Generated calendar sync failed: {type(exc).__name__}: {exc}", flush=True)
        _scheduler_wake.wait(SYNC_INTERVAL_SECONDS)
        _scheduler_wake.clear()


def start_scheduler():
    global _scheduler_thread
    if not SYNC_ENABLED:
        return None
    if _scheduler_thread and _scheduler_thread.is_alive():
        return _scheduler_thread
    _scheduler_thread = threading.Thread(target=scheduler_loop, name="generated-calendar-sync", daemon=True)
    _scheduler_thread.start()
    return _scheduler_thread
